_name_or_path:
    value: /work/hm235/random_transformer/outputs/svd_continual_learning/two_stage_r512_all_seed42/stage1_two_stage_r512_all_seed42/final_model
_wandb:
    value:
        cli_version: 0.19.5
        m:
            - "1": eval/steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": stage2/before/wikitext_ppl
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage2/after/wikitext_ppl
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage2/wikitext_change
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage2/forgetting_pct
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage2/after/tinystories_ppl
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage2/before/tinystories_ppl
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/grad_norm
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage1/after/wikitext_ppl
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage1/improvement
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage2/tinystories_improvement_pct
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": stage2/tinystories_improvement
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 2
                - 7
                - 13
                - 16
                - 19
                - 23
                - 55
                - 62
                - 66
            "4": 3.10.19
            "5": 0.19.5
            "6": 4.57.1
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.5
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_function:
    value: gelu_new
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
apply_svd_to:
    value: all
architectures:
    value:
        - GPT2LMHeadModel
attn_pdrop:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 50256
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
device:
    value: cuda
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: float32
early_stopping:
    value: false
embd_pdrop:
    value: 0.1
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 50256
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 2000
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
experiment_mode:
    value: two_stage
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
from_scratch:
    value: true
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_epsilon:
    value: 1e-05
learning_rate:
    value: 5e-05
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
load_pretrained_path:
    value: null
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /work/hm235/random_transformer/outputs/svd_continual_learning/two_stage_r512_all_seed42/stage2_two_stage_r512_all_seed42/logs
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 100
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: 20000
max_train_samples:
    value: null
metric_for_best_model:
    value: eval_loss
min_length:
    value: 0
model/num_parameters:
    value: 124439808
model_size:
    value: gpt2
model_type:
    value: gpt2
mp_parameters:
    value: ""
n_ctx:
    value: 1024
n_embd:
    value: 768
n_head:
    value: 12
n_inner:
    value: null
n_layer:
    value: 12
n_positions:
    value: 1024
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_return_sequences:
    value: 1
num_train_epochs:
    value: 3
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /work/hm235/random_transformer/outputs/svd_continual_learning/two_stage_r512_all_seed42/stage2_two_stage_r512_all_seed42
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: true
pad_token_id:
    value: null
parallelism_config:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
project_name:
    value: svd_continual_learning
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
reorder_and_upcast_attn:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
resid_pdrop:
    value: 0.1
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: false
save_steps:
    value: 2000
save_strategy:
    value: steps
save_total_limit:
    value: 2
scale_attn_by_inverse_layer_idx:
    value: false
scale_attn_weights:
    value: true
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
stage1_eval_steps:
    value: 2000
stage1_gradient_accumulation_steps:
    value: 4
stage1_learning_rate:
    value: 0.0005
stage1_logging_steps:
    value: 100
stage1_max_steps:
    value: 80000
stage1_model_path:
    value: null
stage1_per_device_train_batch_size:
    value: 4
stage1_save_steps:
    value: 2000
stage1_warmup_steps:
    value: 500
stage1_weight_decay:
    value: 0.01
stage2_eval_steps:
    value: 2000
stage2_gradient_accumulation_steps:
    value: 4
stage2_learning_rate:
    value: 5e-05
stage2_logging_steps:
    value: 100
stage2_max_steps:
    value: 20000
stage2_per_device_train_batch_size:
    value: 4
stage2_save_steps:
    value: 2000
stage2_warmup_steps:
    value: 500
stage2_weight_decay:
    value: 0.01
summary_activation:
    value: null
summary_first_dropout:
    value: 0.1
summary_proj_to_labels:
    value: true
summary_type:
    value: cls_index
summary_use_proj:
    value: true
suppress_tokens:
    value: null
svd_rank:
    value: 512
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.1
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 50257
warmup_ratio:
    value: 0
warmup_steps:
    value: 500
weight_decay:
    value: 0.01
