_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.19
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": linux-x86_64
aa:
    value: rand-m9-mstd0.5-inc1
batch_size:
    value: 128
color_jitter:
    value: 0.4
cutmix:
    value: 1
data_dir:
    value: /work/hm235/random_transformer/data/hf_cache/
dataset:
    value: imagenet
device:
    value: cuda
drop:
    value: 0
drop_path:
    value: 0.1
epochs:
    value: 100
eval_interval:
    value: 5
freeze_blocks:
    value: ""
freeze_qkv_components:
    value: all
freeze_stages:
    value: ""
from_scratch:
    value: true
identity_alpha:
    value: 0.8
identity_beta:
    value: 0.2
img_size:
    value: 224
log_interval:
    value: 100
lr:
    value: 0.0005
min_lr:
    value: 1e-05
mixup:
    value: 0.8
mixup_prob:
    value: 1
mixup_switch_prob:
    value: 0.5
model:
    value: tiny_vit_21m_224.in1k
model_ema:
    value: false
model_ema_decay:
    value: 0.9999
momentum:
    value: 0.9
num_classes:
    value: 100
opt:
    value: adamw
output_dir:
    value: /work/hm235/random_transformer/outputs/tinyvit_experiments/baseline_zeroshot
pretrained:
    value: true
print_model:
    value: false
project_name:
    value: tinyvit_experiments
qkv_identity_init:
    value: none
recount:
    value: 1
remode:
    value: pixel
reprob:
    value: 0.25
run_name:
    value: baseline_zeroshot_seed4
sched:
    value: cosine
seed:
    value: 4
smoothing:
    value: 0.1
train_split:
    value: train
val_split:
    value: validation
warmup_epochs:
    value: 5
warmup_lr:
    value: 1e-06
weight_decay:
    value: 0.05
weight_frozen:
    value: -1
workers:
    value: 8
